version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://perpetua:${DB_PASSWORD}@postgres:5432/perpetua?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    volumes:
      - ../logs:/app/logs
    networks:
      - perpetua-network

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=perpetua
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=perpetua
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - perpetua-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - backend
    networks:
      - perpetua-network

volumes:
  postgres-data:

networks:
  perpetua-network:
    driver: bridge 